pipeline:
   name: drone-with-go
   identifier: drone_with_go
   projectIdentifier: drone_with_go
   orgIdentifier: CI_Training
   properties:
      ci:
        codebase:
          build: <+input>
          connectorRef: account.Jim_Sheldon_GitHub
          repoName: jimsheldon-sandbox/drone-with-go
    
   stages:
      - stage:
          identifier: default
          name: default
          spec:
            cloneCodebase: true
            execution:
              steps:
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: |-
                      go vet
                      go test -v -cover
                    connectorRef: account.Jim_Sheldon
                    image: golang:latest
                    imagePullPolicy: IfNotPresent
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: go build
                    connectorRef: account.Jim_Sheldon
                    image: golang:latest
                    imagePullPolicy: IfNotPresent
                  timeout: ""
                  type: Run
            platform:
              arch: Arm64
              os: Linux
            runtime:
              spec: {}
              type: Cloud
          type: CI
    
