---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  pull: if-not-exists
  image: golang:latest
  commands:
  - go vet
  - go test -v -cover

- name: build
  pull: if-not-exists
  image: golang:latest
  commands:
  - go build

trigger:
  branch:
  - main

...
