---
kind: pipeline
name: default

steps:
- name: test
  pull: if-not-exists
  image: golang:latest
  commands:
  - go vet
  - go test -v -cover

- name: build
  pull: if-not-exists
  image: golang:latest
  commands:
  - go build

# trigger
...
